language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install Flask
  - pip install pymongo
  - pip install requests
# command to run tests
script:
  - pytest test_run.py